### ISSUE TITLE
Profile font is too small

### ISSUE THREAD

**Issue by joaopcbertoldo** [gaogaotiantian/viztracer#112]
The profile font in the `result.html` file is barely readable. I tried to directly change the font size on the CSS using chrome's developer tools but I couldn't figure it out.

Is there a way to customize that?

**Comment by gaogaotiantian** [comment]
Hi, could you elaborate on this issue? Which text do you think is unreadable? The text in the rectangle track? I believe that's generated in canvas, not HTML component.

The font is small but definitely readable to me and we need to take in the fact that we had plenty of information there. Maybe you are using it on a smaller screen like a laptop?

One suggestion I have is to use the "Zoom" feature of chrome. It's in the control menu, or use ``Ctrl + mouse wheel``. Catapult(the front-end of result.html) is responsive so you'll have bigger fonts while keeping the basic structure.

Also, VizTracer is moving it's default front-end to Perfetto now, so that's also an option to try out.

**Comment by joaopcbertoldo** [comment]
Hi, apologies for the poorly-written issue, I wrote it in a hurry to not forget.

I'm talking about this:

![Screenshot from 2021-05-31 18-05-25](https://user-images.githubusercontent.com/24547377/120219064-ef15b100-c23a-11eb-9ef6-f05962ae2e4c.png)

The function names inside the horizontal bars. The screenshot above was taken on a laptop screen, but on a bigger screen it's quite hard to read that. 

I tried
* `Ctrl + +`, `Ctrl + wheel`, zooming but it doesn't scale well
* the new intervace (using `traceviewer`) and it just didn't work with a big trace

>  I believe that's generated in canvas, not HTML component.

So, what does that mean? One cannot change the fontsize once the HTML is already generated? 

> Also, VizTracer is moving it's default front-end to Perfetto now, so that's also an option to try out.

Is that the `traceviewer`-thing?

**Comment by gaogaotiantian** [comment]
Hmm, in my experience, bigger screen normally displays better. Maybe it's different on a 4k screen?

The text being in canvas means you can't simply change css to make it larger. I also believe that to match the track size, you can't easily enlarge the font either.

But the more serious problem is the perfetto front-end. Do you mean ``vizviewer`` when you say ``traceviewer``? The Perfetto front-end is designed for larger trace(GB-level), so in theory it should handler large trace much better than the current catapult trace viewer. Could you tell me what's going wrong when you do ``vizviewer result.json``? Make sure you are using the latest VizTracer(or at least ``0.13.0``) though.

The Perfetto front-end also scales much better with Chrome zoom.

For example, this is my screen shot of 150% zoom on a 2k screen.

![image](https://user-images.githubusercontent.com/13121107/120221297-0466ed00-c1f3-11eb-9f7f-cfd96c2f4e2f.png)
