### ISSUE TITLE
OSError: [WinError 10013] forbidden by its access permissions

### ISSUE THREAD

**Issue by GitHunter0** [gaogaotiantian/viztracer#138]
Hi folks, I'm receiving the error message below when I try to run `vizviewer result.json` . Any idea how to solve this? 

```     
Traceback (most recent call last):
  File "c:\users\...\miniconda3\envs\py38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\...\miniconda3\envs\py38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\...\miniconda3\envs\py38\Scripts\vizviewer.exe\__main__.py", line 7, in <module>
  File "c:\users\...\miniconda3\envs\py38\lib\site-packages\viztracer\viewer.py", line 160, in viewer_main
    ret_code = view(
  File "c:\users\...\miniconda3\envs\py38\lib\site-packages\viztracer\viewer.py", line 123, in view
    with socketserver.TCPServer(('127.0.0.1', port), Handler) as httpd:
  File "c:\users\...\miniconda3\envs\py38\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "c:\users\...\miniconda3\envs\py38\lib\socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
```

My settings:
```
Windows 10 Pro
python 3.8
conda 4.10.3
viztracer 0.13.4
I'm the admin of my computer.
```

**Comment by gaogaotiantian** [comment]
Hi @GitHunter0 , this is not a vizviewer specific issue. I believe this means you don't have access to 9001 port. One of the possibilities is that there are some other processes occupying the port. It could also be your firewall/anti-virus software that blocks vizviewer to access the port. I would suggest Google this error and try to find reasons/fixes for the issue. The error message simply suggests that you can't access the socket, nothing specific to vizviewer.

For example, there's a stackoverflow thread for the error - https://stackoverflow.com/questions/15619921/an-attempt-was-made-to-access-a-socket-in-a-way-forbidden-by-its-access-permissi

**Comment by GitHunter0** [comment]
Thank you for the feedback @gaogaotiantian.
Actually I've seen the google/stackoverflow issues but they could not solve my problem.
- Is there a way to change viztracer port?
- Would you consider providing commands to run viztracer from inside python instead of terminal?

**Comment by gaogaotiantian** [comment]
For now you can't change the port mainly because of Perfetto's security model. I can change that on the Perfetto side, so far I have not seen a reason to do it.

You can run viztracer inside python, check ``Inline`` section in README, or check it in the docs. Unless you mean something else?

**Comment by GitHunter0** [comment]
> You can run viztracer inside python, check `Inline` section in README, or check it in the docs. Unless you mean something else?

I mean a way to launch/run `result.json` from python and to have the ability to do everything without the need to use a terminal.

> For now you can't change the port mainly because of Perfetto's security model. I can change that on the Perfetto side, so far I have not seen a reason to do it.

I asked because then maybe my access permission error would be solved. I really wanted to be able to use `viztracer`

**Comment by gaogaotiantian** [comment]
What do you mean by launching the report from python? You need a web browser to view the report anyway. ``vizviewer`` is just a script to host an HTTP server and load the data. You can check the code in https://github.com/gaogaotiantian/viztracer/blob/master/src/viztracer/viewer.py , it's not officially documented but it should be pretty easy to just call the ``view()`` function in your python program to host the server. You won't need to open a "terminal", but you need to open web browsers. Just notice that if you do this in the same process, it will halt your process as it's dealing with the HTTP requests.

Another way to do it is simply use ``subprocess`` to open a ``vizviewer`` process from python, which is basically the same path to do vizviewer, but "in Python".

I'm not sure why you don't want terminal involved, I always develop python with an environment with easily accessible terminal, but maybe that's not the case for you? If you could elaborate on your specific case maybe I could help or improve VizTracer in some situation that I have not thought of.

As for the arbitrary port, if you know that 9001 is occupied by some program, then yes it would solve your problem. Otherwise it won't be helpful. A quick way to check it is to write a small Python program to bind 9001 with socket and make sure it FAILED. Then try 9002 and see if that works. I will make the port assignment more flexible in the next release, but at least this is something to narrow down the problem.

Also, if you are using Windows, ``netstat`` could be a helpful tool to check if the port is occupied.

**Comment by GitHunter0** [comment]
I appreciate the feedback @gaogaotiantian , I will work on that. Since the issue is not viztracer related, I'm closing this for now.
