### ISSUE TITLE
not working in colab

### ISSUE THREAD

**Issue by Rumi4** [gaogaotiantian/viztracer#147]
tried using it in colab notebook but the viztrace magic seems not working

**Comment by gaogaotiantian** [comment]
There are a couple of things related to this issue:
1. We do not officially support colab for now as it is not popular enough - this is the first issue about it and this is also the first time I heard about colab.
2. The fundamental reason colab is not working at this point is because it uses an outdated IPython version(I think it's 5.5 while the latest is 7.26?).
3. Even if VizTracer tracing works(which I may or may not be able to achieve with older IPython), I doubt if the viewer part works. The existing viewer requires an HTTP server hosted and ``webbrowser`` package to open a new tab, which both could be potential security issue if the Jupyter notebook is hosted remotely.

From the reasons above, I will not proceed to make VizTracer work with colab. I may adapt VizTracer to colab or other popular online runtimes in the future if it could potentially work.
