### ISSUE TITLE
tracing python script with matplotlib 

### ISSUE THREAD

**Issue by chritter** [gaogaotiantian/viztracer#181]
Hello,

When using viztracer on a Python script which plots matplotlib figures I found that only the matplotlib execution stack appears in the viztracer UI while the other parts of the code are not visible. 
Example:
https://github.com/scikit-learn/scikit-learn/blob/main/examples/ensemble/plot_stack_predictors.py

Is this expected and is there a workaround? Thanks!

**Comment by gaogaotiantian** [comment]
So there are multiple things involved in this issue.

1. The reason you only saw ``matplotlib`` code is probably because the buffer is filled. There used to be a warning about it, but in the code reconstruction some of them is missing, I'm working on that. The space(both memory and disk) viztracer needs grows linearly with the execution time, so it's impossible to recording everything during all the time. The default choice is to save whatever is the latest. For this matter, I would recommend to use filters to filter out some data out that you don't need(especially for profiling purpose). Some filter you might look into is ``max_stack_depth``, ``min_duration`` or maybe ``ignore_c_function``. Of course you can increase the trace buffer by ``--trace_entries <buffer size>``, the default is 1000000. However, ``Perfetto``, the front-end viztracer uses, can't handle infinite large trace data either, so there's an upper limit there(and the limit from your RAM/disk).
2. ``sklearn`` uses ``loky`` for its parallel backend, which, thanks to @ogrisel, supports ``viztracer`` out of the box. However, there's an ordering issue. ``viztracer`` requires all the sub-processes to finish before it collects trace, to have all the data from its sub-processes. However, it seemed like they way ``sklearn`` uses ``loky`` will shut down the workers after the main process is down. This conflict results in a weird issue - ``viztracer`` would think there's only one process, because the process workers are still alive, when the main process is down(or right before the main process is down). I did not look too much into the mechanism ``loky`` or ``sklearn`` uses to do parallel work, so I don't know if this is solvable.

However, the sub-process data is saved somewhere. I'm working on a work-around for the users to manually specify a folder to save the data, then combine the data themselves, which in this case could solve the problem mentioned above, with a very minor effort from the user.

Please let me know if you have other questions!

**Comment by gaogaotiantian** [comment]
Interestingly enough, ``loky`` + ``viztracer`` actually works on python3.9+.

**Comment by gaogaotiantian** [comment]
#182 is merged to master which supported ``loky`` + ``viztracer`` on all python version. You should be able to see all the processes now. I'll work on warning messages, but feature wise this issue is solved.

You can try master version ``viztracer`` with ``pip install git+https://github.com/gaogaotiantian/viztracer``

**Comment by gaogaotiantian** [comment]
I updated the warning message in #184 as well, so you should be able to see the warning when the buffer overflows. I believe I addressed all the issues in this issue.
