### ISSUE TITLE
ipywidgets button on_click event is out of date

### ISSUE THREAD

**Issue by aaronzs** [gaogaotiantian/viztracer#213]
I was using viztracer cell magic in jupyter lab, and encounter this error.

```
TypeError                                 Traceback (most recent call last)
File .../python3.8/site-packages/viztracer/cellmagic.py:23, in VizTracerMagics.viztracer.<locals>.<lambda>(b)
     20 server = ServerThread(file_path)
     22 button = Button(description="VizTracer Report")
---> 23 button.on_click(lambda b: server.view(file_path, once=True))
     25 display(button)

TypeError: view() got an unexpected keyword argument 'once'
```

It seems like the on_click event is out of data

`lambda b: server.view(file_path, once=True)` -> `lambda b: server.view()`

**Comment by gaogaotiantian** [comment]
You are right and I realized that a couple of days ago. The ``master`` version is fixed by https://github.com/gaogaotiantian/viztracer/commit/ff308560edd8b5e44d1de0bd36de13d8e2ed238a, but it's not released yet. I think the next release should be pretty soon. You can use the ``master`` version for now or wait for a couple of days for the new version.

Sorry about the trouble!
