### ISSUE TITLE
jupyter magic on remote server failed

### ISSUE THREAD

**Issue by pluto-the-lost** [gaogaotiantian/viztracer#221]
Hi, thanks for the amazing package!

I was using jupyter notebook on a remote Centos server, linked with ssh channel. I tried the cell magic
```
%%viztracer
# my function
```
the button show up but there was an error when I clicked it

![image](https://user-images.githubusercontent.com/38177789/160783568-50d3399f-1675-4fe9-8ef3-5d7d7cbee7d3.png)

I don't have a python environment in my local machine, so I don't know how to use the json file neither. My current solution is to use 

```
with VizTracer(output_file="viztracer_report.html") as tracer:
    # my function
```

Then the html file can be downloaded and viewed in browser. I wonder if there is a solution that I can use the magic without have to download a html file, this can be much more convinient.

**Comment by gaogaotiantian** [comment]
The error message shows that the port was already in use. VizTracer uses port 9001 for the viewer, so double check if any other process on your remote server is using that port.

**Comment by pluto-the-lost** [comment]
9001 is used and I changed the port to another unused port (by replacing 9001 in viewer.py by 1235), this time nothing happened when I clicked the button

![image](https://user-images.githubusercontent.com/38177789/160992457-942044b1-2ccc-4ab6-a394-591714ea009e.png)


and the 1235 port is not listened neither

![image](https://user-images.githubusercontent.com/38177789/160992333-212ece0a-24e7-4c38-8122-a11e63165c36.png)


Is there any tutorial for using viztracer on remote server? I did not find it in documentations.

BTW, I installed jupyter on my local machine and viztracer magic works well locally.

**Comment by gaogaotiantian** [comment]
I'm not that familiar with Jupyter or the remote usage. There could be a number of things that won't work. Basically viztracer should host an http server and open a browser tab to show it. It's possible that in remote server, you can't open webbrowser module to open a new tab? Or it might already did that, but the tab was opened remotely, instead of on your browser.

I'm not able to reproduce this issue as I don't own a remote Jupyter setup. There's not enough information for me to diagnose. I do wish that I could help in this case, but for now I don't think I can.

**Comment by pluto-the-lost** [comment]
Well then I will use the first solution of downloading html, not a vital problem. Thanks for answering and also thanks for the good work again.

**Comment by gaogaotiantian** [comment]
I would suggest saving to a `json` file and use local `vizviewer` to visualize that. `html` is deprecated at this time and `json` + Perfetto is much more powerful.
