### ISSUE TITLE
Profiling generators

### ISSUE THREAD

**Issue by niasie** [gaogaotiantian/viztracer#225]
Hey,

I'm currently using VizTracer to profile an ML model using TensorFlow and I really like it so far. 

This is my issue:
I load my data into a `tf.data.Dataset` using a generator (`tf.data.Dataset.from_generator`) and iterate over it. I would like to profile this. However, when simply calling the model using `viztracer`, it does not show up in the report. The trace only goes down till the built-in `_next_internal` methods. I have also tried adding the `@trace_and_save` decorator to my generator methods. However, VizTracer generates a new report with every call to `next`, which is not very useful.

Does anyone have a suggestion how to get profiling inside my generator? Thanks!

**Comment by gaogaotiantian** [comment]
The description is very vague. What's `this` and what's `it`? `@trace_and_save` it a decorator to trace a function then dump the trace data out to a file, which is exactly what it's doing here.

Do you want to dig into your generator? Could you share the code of your generator? Also not to be disrespectful, do you have a relatively good understanding of how generator works in Python? I asked this because, each `next()` or `iter()` call to the generator should normally be very short (from yield to yield). Why do you think your generator call is the bottleneck of your program and try to profile it?

If possible, could you share a minimum demo for your issue so I can reproduce it and see what happened, or a screenshot of your vizviewer report that is zoomed into the part that you were interested in? That would be useful for me to understand the problem.

**Comment by gaogaotiantian** [comment]
Close due to inactive.
