### ISSUE TITLE
Best practice of profiling execution across multiple processes 

### ISSUE THREAD

**Issue by jiaodong** [gaogaotiantian/viztracer#232]
Code to reproduce, with [Ray Nightly Wheel](https://docs.ray.io/en/master/ray-overview/installation.html#daily-releases-nightlies)

Code to reproduce profiling

https://gist.github.com/jiaodong/62a86e1f57887cfb96ee1f34e4df389b

Tracing across boundary of processes can be tricky. In this case, my workload is starting multiple `Actor` that each has its own process not directly spawned by python's multiprocess module. 

I'm trying to profile `ray.get(dag_handle.predict.remote(0))` that resolves the `ObjectRef` formed by multiple nodes' executor (a bit similar to future) but then i lose visibility into the actual execution path, even though I got some useful hints of execution cost from the long, short tails at the beginning. What's the best practice to profile this type of workload ?

<img width="1470" alt="Screen Shot 2022-05-02 at 3 17 10 PM" src="https://user-images.githubusercontent.com/6372689/166357049-ff8d2c58-8a93-4bfb-97ce-449faec0de6f.png">

<img width="1455" alt="Screen Shot 2022-05-02 at 3 17 20 PM" src="https://user-images.githubusercontent.com/6372689/166357304-9b331173-09cd-4222-bb9d-f3adab9498e8.png">

**Comment by gaogaotiantian** [comment]
VizTracer patches some common packages to enable multiprocessing tracing, for example, `multiprocessing`, `subprocess` and even `os.fork()`. However, it can't work in some circumstances. One that I know was when you use `os.exec*` family to spawn a new process - there's no way VizTracer can invoke itself after the function.

`loky` had a similar issue so I provided a general solution to this. First, you need to know when your new process is spawned, and you need a way to communicate between your spawned process and it's parent. What you need to do to make VizTracer work is:

1. In your parent process, get `init_kwargs` with

```python
from viztracer import get_tracer
init_kwargs = get_tracer().init_kwargs
```

2. `init_kwargs` would be a vanilla `dict` which could be pickled(or serialized in other way). You need to send this to your spawned process.

3. In your spawned process, before everything starts to run, do

```python
tracer = VizTracer(**init_kwargs)
tracer.register_exit()
tracer.start()
```

where ``init_kwargs`` is the `dict` received.

This piece could be found in the [documentation](https://viztracer.readthedocs.io/en/latest/concurrency.html#generic-multi-process-support)

You can also refer to the PR of loky to enable VizTracer - https://github.com/joblib/loky/pull/299

This should provide generic support any 3rd party multi-process library. However if you think `ray` is using a very common Python built-in scheme which should be covered by VizTracer, let me know and we can discuss that.

**Comment by jiaodong** [comment]
Thanks for the detailed instruction and fast response @gaogaotiantian :) I think this could work with Ray given Ray also pickles the function / class along with args, and we have some python binding for Actor spawning both at Ray and user constructor level. Let me give a shot at this later and will reply back here with my findings, thanks !

**Comment by CiaranWelsh** [comment]
Hello. I have a similar issue. viztracer works great with multithreading but not so well with multiprocesses (yet). I've tried this solution but `get_tracer` returns None. Any ideas why? Thanks

**Comment by gaogaotiantian** [comment]
Hi @CiaranWelsh, like I mentioned above, you need to explicitly add support for multiprocess libraries. Which multiprocess library are you using? VizTracer supports all the built-in multiprocess libraries natively, but if you are using some other library that's based on something like `os.execv`, then it won't "just work".

Also, how did you start tracing? Did you use the command line by `viztracer your_program.py`? If you are using inline version, there's no chance for viztracer to patch the libraries so multiprocess won't be supported.

That's said, it might be easier for me to explain if you can share more information. A minimum demo would be nice.

**Comment by CiaranWelsh** [comment]
@gaogaotiantian Thanks for getting back to me so fast. I'm using `multiprocessing.Process` but its kind of hard to abstract into a MWE (sorry). It turns out if I use the command line version it does works as expected. The inline version which I was trying to use for isolating only part of my program does not, but given your comment bove I think this is expected. 

The only problem I get is when writing the output from viztracer to file seems to crash Python when my input data is big. Briefly, I'm basically reading binary data from a file, when the file is big Python crashes before the data is written. Not to worry, I can optimize with a smaller file and all works well. 

Thanks for providing this incredibly useful tool! Best, 
Ciaran

**Comment by gaogaotiantian** [comment]
@CiaranWelsh yes the inline version does not support multi process natively because it has to patch the `multiprocessing` library before you use it. Crashing Python is a bit weird unless you are out of memory. One interesting thing to test is to set `--tracer_entries 10` to only record 10 function entries and see if that will still crash Python. However, for the actual use case, using a smaller file might be the way to go anyway, unless your problem ONLY appears with large inputs.
