### ISSUE TITLE
`RPC Framing Error` on Firefox

### ISSUE THREAD

**Issue by ajyoon** [gaogaotiantian/viztracer#237]
When I attempt to view a trace in Firefox, I get the following error in the browser:

```
Trace: http://127.0.0.1:9001/localtrace

Viewed on: http://127.0.0.1:9001

Error: RPC framing error
onRpcResponseMessage@http://127.0.0.1:9001/v23.0-50554e3ba/frontend_bundle.js:79104:19
onRpcResponseBytes@http://127.0.0.1:9001/v23.0-50554e3ba/frontend_bundle.js:79064:18
onMessage@http://127.0.0.1:9001/v23.0-50554e3ba/frontend_bundle.js:79395:15


v23.0-50554e3ba 50554e3ba962944f0d6412e5dca5aca1c9f8c0b6
UA: Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0
```

Viztracer version is `0.15.1`. The page loads fine in Chromium `Version 101.0.4951.41 (Official Build) Arch Linux (64-bit)`

I noticed that I can open a very simple "hello world" program trace in Firefox just fine, the error only pops up when running on my production code.

**Comment by gaogaotiantian** [comment]
This is a known issue #139.

We are not going to "solve" this because this is unlikely a VizTracer issue. It's most likely an issue with either FireFox's resource allocation or Perfetto(`vizviewer`'s UI)'s compatibility. It's worth mentioning that Perfetto is a Google's project so it should not be surprising that it works better with Chrome(and all other Chromium based browsers).

For now I can only suggest to use Chrome for the trace logs, if that's not too much trouble for you.

**Comment by ajyoon** [comment]
Thank you for the explanation; the Chromium workaround works fine.
