### ISSUE TITLE
Is it possible to use `orjson` in `snaptrace`?

### ISSUE THREAD

**Issue by skyline75489** [gaogaotiantian/viztracer#274]
Currently the builtin `json` is used in `fprintjson`:

https://github.com/gaogaotiantian/viztracer/blob/863d585d4f499e2ca7d120c98860399806a7b71e/src/viztracer/modules/util.c#L18-L25

Is it possible to use `orjson` to speed up the `dumps`?

**Comment by gaogaotiantian** [comment]
`viztracer` has no required dependency and that's on purpose. Most of the `viztracer` users won't have `orjson` on their projects. We could add a check here to use `orjson` if they do have one, but `fprintjson` is not on the critical path. In most cases, it won't even be used at all. It's not worth the extra effort to check for `orjson` and use that instead of the built-in `json`.
