### ISSUE TITLE
Global viztracer returning None doesn't play nicely

### ISSUE THREAD

**Issue by zplizzi** [gaogaotiantian/viztracer#309]
The docs say 
```
# get_tracer() will return None if no tracer is registered
tracer = get_tracer()
```

But this doesn't work so well, because I'll do something like `tracer.log_instant("stuff")` in my file, and will get the error 
`AttributeError: 'NoneType' object has no attribute 'log_instant'`
if the tracer isn't registered.

This isn't ideal - I'd like my viztracer annotations to work if i'm running the script with `viztracer myscript.py` and just silently do nothing if i'm running it with `python myscript.py`, but with this behavior my script is just broken if I don't run it with viztracer. So I think `get_tracer()` should return a dummy no-op tracer, instead of `None`, in the case that the tracer isn't registered.

**Comment by gaogaotiantian** [comment]
Having `get_tracer()` return a dummy object also has its own issue - for example, there's no straightforward way to determine whether tracer already exists in the process. Some of the viztracer features depend on `get_tracer()` returning `None` now.

For most of the time, I prefer explicit than implicit, which means I like
```python
if tracer:
    tracer.log_instant("stuff")
```

However, I can totally understand that you want your code to perform normally with `python` and log with `viztracer`. There's actually a solution to that - magic comment.

You can do
```python
# !viztracer: log_instant("stuff")
```
in your code, which is a valid comment in python so python will never execute it (real no-op rather than no-op that costs). `viztracer --magic_comment myscript.py` will magically convert that to a logging command and log properly. You can refer to the [docs](https://viztracer.readthedocs.io/en/latest/custom_event_intro.html#magic-comment) for more usage.

**Comment by zplizzi** [comment]
Ah, this is great, sorry for not reading far enough down in the docs!
