### ISSUE TITLE
Feature request: option to use firefox profiler as an alternative perfetto.dev

### ISSUE THREAD

**Issue by ogrisel** [gaogaotiantian/viztracer#332]
https://profiler.firefox.com/ is a neat alternative to perfetto to interactively explore recorded profile traces.

It can load local trace files in the browser as perfetto (or speedscope) with a similar interactive UI.

I assume that this could also serve as a better workaround for the `RPC Framing Error` observed when using perfetto to load viztracer files on firefox. See: #139, #237 and #317.

Furthermore, it has a button to share URLs to tracefiles online (e.g. in github issues) without the reader having to download and reload a json tracefile manually. Here is an example of such a shared link (with a Python program trace generated by `samply`, see below):

- https://share.firefox.dev/43KFFDO

profiler.firefox.com is notably used by the [samply](https://github.com/mstange/samply) profiler if you want to give it a quick try on an arbitrary local program execution (with native calls). Note that as of now, samply is not Python-source aware but this can still serve as an example on how to do profiler.firefox.com integration for viztracer.

**Comment by gaogaotiantian** [comment]
First of all, thanks for the recommendation. I'm actually aware of the tool before I even started developing viztracer :)

The fundamental issue here is - viztracer is a tracer that can be used for profiling, it's not a profiler. I've written an [article](https://python.plainenglish.io/whats-a-tracer-and-how-s-that-different-from-a-profiler-75a044f8caf4) talking about this.

Firefox profiler is not designed to show trace data - you can try to load a trace file from viztracer and see your self. They claim to support Chrome trace format, but it's not showing anything. No stack relation, no process by process view (so that you know the relations between processes/threads).

Same thing with speedscope, it's designed for showing profiling data, and you can easily crash it with a 100M file, which perfetto handles easily.

Actually, perfetto is the only tool I know that fits viztracer's purpuse - to show details of every single function call on a timeline with support for multi-thread and multi-process(not show them in different tabs, that's not helpful).

All the other visualization tools on the market basically only focus at functions that take the most of time - which is fine because that's what a profiler normally does, but viztracer needs more, compared to the full-time profiling tools like py-spy.

Yes, you can crash perfetto on firefox with a large trace file, but you can easily crash other tools with a trace file that's 10x smaller - you can try to load a ~100M file generated by viztracer on firefox profiler and check the result.

Let me know if you have more questions :)

**Comment by ogrisel** [comment]
Alright then, thanks for the explanation. It would be great if perfetto had a button to easily share reports though.

Anyway, closing this.

**Comment by gaogaotiantian** [comment]
That would require plenty of free disk space from Google :)
