### ISSUE TITLE
No reminder of port conflict when using the parameter "--use_external_processor"

### ISSUE THREAD

**Issue by JiangShanCode** [gaogaotiantian/viztracer#393]
When I use "vizviewer --use_external_processor result.json," everything appears to be fine, and I use SSH to forward port 10000 from the remote to port 10001.
![image](https://github.com/gaogaotiantian/viztracer/assets/53932468/241b16f1-ca9f-4ac4-ab72-d3d6d1519ec1)
However, I can't open the JSON with Edge and get the errors.
```
To assist with debugging please attach or link to the trace you were viewing.

Viewed on: http://localhost:10001

TypeError: Failed to fetch
TypeError: Failed to fetch
    at http://localhost:10001/v37.0-a9e8e2a6b/frontend_bundle.js:434774:10

v37.0-a9e8e2a6b a9e8e2a6bab034d82281d511929eedd6eb30a9e2
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
```
Nevertheless, when I use "vizviewer result.json," it informs me of a port conflict, and everything is resolved when I change the port.
![image](https://github.com/gaogaotiantian/viztracer/assets/53932468/1b5f1bf9-11c4-42d4-87e6-b39b64a94e86)
Furthermore, I discovered a port conflict on the remote machine.
![image](https://github.com/gaogaotiantian/viztracer/assets/53932468/89cb3c65-3375-4d90-b1fb-ea8d2a2ebd84)
The version of viztracer is 0.16.1.

**Comment by gaogaotiantian** [comment]
`external_processor` only takes requests from `localhost:10000`, I doubt if it works well with remote port fowarding -> perfetto will make a request to `localhost:9001` which should be your local external processor but it won't have access to it because it's remote. Remote part is not tested thoroughly for vizviewer and Perfetto probably does not take care of this case. If you are using remote, I would suggest do it with http processor because it's self-contained.
