### ISSUE TITLE
Uncaught compile error when attempting to view traces using vizviewer

### ISSUE THREAD

**Issue by awchisholm** [gaogaotiantian/viztracer#424]
**Ubuntu 22.04**

**Python packages:**
objprint   0.2.3
orjson     3.10.0
pip        23.1.2
setuptools 67.8.0
viztracer  0.16.2
wheel      0.40.0

**Code:**
`print('hello world')`

**Detailed error:**
Uncaught CompileError: WebAssembly.Module(): Compiling function #60:"std::__2::enable_if<(__is_cpp17_forward_iterato..." failed: Wasm SIMD unsupported @+19704

v37.0-a9e8e2a6b a9e8e2a6bab034d82281d511929eedd6eb30a9e2
UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**JSON file:**
[result.json](https://github.com/gaogaotiantian/viztracer/files/14951020/result.json)

**Comment by gaogaotiantian** [comment]
Your json file looks fine. What browser did you use to open this? Do you have a screenshot?

**Comment by awchisholm** [comment]
Chrome, Firefox and whatever VSCode uses, all failed with the same error. However, I tried on a more modern machine and it worked. I suspect there is a CPU issue since my old machine is some 10 years old and lacks some specific features. I had a similar problem with Tensorflow that eventually was explained by this (although I did not keep the details unfortunately). Perhaps one of the packages being used has a similar deep-down requirement?

So my immediate issue has gone away.

**Comment by gaogaotiantian** [comment]
The viewer is basically [Perfetto](https://ui.perfetto.dev/) with some customization. If the original Perfetto won't work then there's nothing viztracer can do about it. Yes it's possible that this is due to a very old CPU - Perfetto might've used some SIMD operations that the old CPU does not support and they might not care about the incompatibilities of the old CPUs.

As of now, I'll close this issue because it does not seem like a viztracer issue. If you can somehow use the original Perfetto, let me know and I can reopen this for further investigation.
