### ISSUE TITLE
doesn't pick up existing threads at launch

### ISSUE THREAD

**Issue by gedalia** [gaogaotiantian/viztracer#437]
I just noticed that viztracer can't capture already running threads, only ones that have launched after tracing has started. seems like it would be a nice addition. Looks like 3.12 might have added functions that would enable it to happen (see threading.settrace_all_threads)

**Comment by gedalia** [comment]
I was imagining hasattr could be used to decide if a feature was available, we're actually on 3.10 not 3.12, but figured I could be forward looking. It's interesting that you think of it as a mainly CLI tool. I have it hooked into our gui so it can be started and stopped at will, in general I frequently only get a second or two of info before I blow through the buffer, so there's no way I could use the CLI. 
I often use the tools like this just to understand systems I'm not that familiar with, works a bit better with https://github.com/wolfpld/tracy which can handle much larger captures.

**Comment by gaogaotiantian** [comment]
I'm not saying this is unsolvable. I'm just not sure tracing at an arbitrary point of a thread generates good data.

I do think of it as a CLI tool, because all the multi-process features rely on it anyway. You won't be able to trace multiprocess programs with inline usage.

The tool probaly will be a bit confused (not a lot) if you have return events that do not correspond to a start (imagine you are deep in the call stack and you start the tracing).

However, if you do want something like that, maybe try to create a single tracer as soon as your GUI started - it will hook the threadings. Then use `start()` and `stop()` to collect trace, instead of creating a new tracer every time the user wants to trace.

**Comment by gedalia** [comment]
hm that's an interesting idea that I hadn't realized was possible, will give it a try

**Comment by gaogaotiantian** [comment]
Hi @gedalia , just want to let you know that I finally found a good reason to simply collect all data from all threads after 3.12 by default - VizTracer is using `sys.monitoring` now on Python3.12+ which natively support multi-thread tracing. Limiting it on a single thread takes more efforts, not less. So from the next release, You can trace all threads, no matter if they are created after VizTracer.

**Comment by gedalia** [comment]
Cool, we’re on 3.10 but will hopefully move up eventually. I’ve also played
with binding python to Tracy, gets much less information but has lots of
stats which are handy for evaluating perf changes. But even there I need to
start with viztracer to figure what code is being run.
