### ISSUE TITLE
named args with -m

### ISSUE THREAD

**Issue by randomseed42** [gaogaotiantian/viztracer#484]
for below code, I can run with `python main.py -m 10`, when I use `viztracer main.py -m 10`, it will raise `ImportError: No module named 10`, so maybe we can dive deep how python deal with the `-m` arg by position?

```py
import argparse


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-m', '--month', help='Month')
    args = parser.parse_args()

    print(f'Month is {args.month}')


if __name__ == '__main__':
    main()
```

**Comment by gaogaotiantian** [comment]
Because Python itself does not use `argparse` for argument parsing. We will not rewrite all the parsing code in C. `argparse` is not sensitive to the order of the arguments, so it's not trivial to consider all the options after the script as the arguments to the script itself. Besides, it might be helpful for users to do `viztracer script.py --open`, where appending `--open` after the script would be simpler.

The best way to resolve ambiguity is to be explicit, and in this specific case, I think `--` is to way to do that, not heuristics (it's difficult to even define the behavior properly and it's even more difficult to implement it).

**Comment by randomseed42** [comment]
Totally agree and it do make sense to use long version `--month` in such kind of scenario. Thanks for the prompt response!
