### ISSUE TITLE
Timing off?

### ISSUE THREAD

**Issue by maartenbreddels** [gaogaotiantian/viztracer#50]
I have this code in my jupyter notebook:
```python
from viztracer import VizTracer
tracer = VizTracer()
tracer.start()

def go():
    for i in range(1000):
        widgets.Layout()
go()
tracer.stop()
tracer.save()
```

This results in:
![image](https://user-images.githubusercontent.com/1765949/99544401-8ceb1200-29b4-11eb-9e63-e4a387e23cc1.png)

Where `go` gives me:
```

Start | 13,000 ns-- | --
Wall Duration | 4,297,617,000 ns
Self Time | 3,553,028,000 ns

```

As if most time is spend in go itself, and only 700msec in the constructor of Button (and the rest), which i find highly unlikely.

However, if I select one of the constructor calls:
![image](https://user-images.githubusercontent.com/1765949/99544712-e9e6c800-29b4-11eb-9a34-563ce96c4df8.png)

It shows it takes 3ms, so 1000 calls should take ~3seconds. It seems like this does not add up.  Is maybe something like systemtime not taken into account? Or am is making a mistake?

**Comment by gaogaotiantian** [comment]
If you take a look at the first graph, you will notice that there's a big gap before the dense log. That's because, due to the nature of VizTracer, it can't keep record of everything that ever happened with limited memory and disk space. Unlike the "profilers" like cProfile, which only need to record the count of each function, VizTracer needs to record every single entry and exit of each function.

VizTracer used a circular buffer to record the entries, and it's just wrapped. (I think there should be a notice in the command line console). The default buffer size is 1 million entries(https://viztracer.readthedocs.io/en/latest/basic_usage.html#circular-buffer-size), you can change it to a bigger size. However, even if you have a huge disk space, Chrome is not able to deal with a report with too many entries(~ 10 million on 16G RAM according to my experience). So the incorrect timing data is because of the missing data during the time.

I'm not sure what's your purpose here, I would assume mainly for entertaining(because unlike some other statistical profilers that require multiple runs for a function to be accurate, VizTracer only needs one), but if you do need something like this, to construct an object 100 times and try to check the CPU/Wall time, you should try filters. 

You can't have all the details for all the functions with limited resource, so maybe you don't need the details? ```--max_stack_depth``` would be my first recommendation, because it's straightforward and is designed for cases like this. You can always do ```--ignore_c_function``` to strip off log of builtin calls which are normally the branch detail of the project. 

If you have some actual goals to accomplish here, please do not hesitate to comment here :)

**Comment by maartenbreddels** [comment]
Thanks, indeed when I just do 10 or 100 I don't get that warning and it all adds up. The reason I was doing 1000 was to compare it to a normal run.

**Comment by gaogaotiantian** [comment]
Yeah you can still do 1000 as long as you use some proper filters to limit each construct record under 1000. You'll get a ballpark, not the every details. And it's probably helpful for the overhead. 

Anyway, if you are satisfied with the answer, feel free to close the issue :)

**Comment by maartenbreddels** [comment]
Thanks a lot, excellent tool!
