### ISSUE TITLE
Use `__rdtsc` to get a much better overhead

### ISSUE THREAD

**Issue by gaogaotiantian** [gaogaotiantian/viztracer#510]
Getting the timestamp contributes to the majority of the overhead now. We could use `__rdtsc` to get a much better overhead.

**Comment by FindDefinition** [comment]
I'm using `baseTimeNanoseconds` in pytorch profile result and `time.time_ns() - time.monotonic_ns()` to align timestamps between viztracer and pytorch. If viztracer use `__rdtsc`, how can I get accurate epoch time from `__rdtsc` timestamp?

**Comment by gaogaotiantian** [comment]
Ah, I finally got what that field means. `VizTracer` will support PyTorch natively, it will deal with the offset. Also with `__rdtsc()`, it will have a way to sync to a clock as well.

**Comment by FindDefinition** [comment]
The problem is if I want to attach custom event with custom tid/pid such as flow event (viztracer don't support this) by append event json to `traceEvents`, I can only access epoch/monotonic time in python API. so I need a API to get viztracer offset such as `baseTimeNanoseconds` in pytorch, at least some API like `time.time_ns() - viztracer.viztracer_time_ns()` to convert viztracer timestamp to epoch time.
There is a function called `getts` in snaptrace, is this enough to convert viztracer timestamp to epoch time?

**Comment by gaogaotiantian** [comment]
There will be a `get_time_base()` API provided by `viztracer`. Working on it now.
