### ISSUE TITLE
run viztracer  against python2.x  appplication

### ISSUE THREAD

**Issue by sosogh** [gaogaotiantian/viztracer#57]
Hi

```
root@controller:~# python  --version
Python 2.7.12

root@controller:~# pip --version
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
pip 20.3 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
```

Does viztracer support python2.x ?  I got errors when running  `pip -vvv install  viztracer`

``` 
Link requires a different Python (2.7.12 not in: u'>=3.6'): https://files.pythonhosted.org/packages/1d/38/078b2fe674f1a47d88d860c81b288f182265f56a26b096c6181f6d7547f2/viztracer> -0.10.4.tar.gz#sha256=ceb7464a3f25bffff675904ae5d66bb0b81188b2d21ec147aa32d1d4931b954f (from https://pypi.org/simple/viztracer/) (requires-python:>=3.6)
 Given no hashes to check 0 links for project 'viztracer': discarding no candidates
ERROR: Could not find a version that satisfies the requirement viztracer (from versions: none)
 ERROR: No matching distribution found for viztracer
```

If it not , is it possible to run viztracer  against python2.x  appplication ?
for example , I install openstack nova-api  via `apt-get install nova-api`.
And  the nova mudules are located at `/usr/lib/python2.7/dist-packages/nova/ `

Finally, I install viztracer via pip3 , and run viztracer against nova-api, I got error:
 
```
root@controller:~# viztracer  /usr/bin/nova-api --config-file=/etc/nova/nova.conf --log-file=/var/log/nova/nova-api.log
Traceback (most recent call last):
  File "/usr/local/bin/viztracer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/viztracer/main.py", line 372, in main
    success, err_msg = ui.run()
  File "/usr/local/lib/python3.5/dist-packages/viztracer/main.py", line 201, in run
    return self.run_command()
  File "/usr/local/lib/python3.5/dist-packages/viztracer/main.py", line 300, in run_command
    return self.run_code(code, main_mod.__dict__)
  File "/usr/local/lib/python3.5/dist-packages/viztracer/main.py", line 250, in run_code
    exec(code, global_dict)
  File "/usr/bin/nova-api", line 6, in <module>
    from nova.cmd.api import main
ImportError: No module named 'nova'
Loading finish                                        
Saving report to /root/result.html ...
Dumping trace data to json, total entries: 41140, estimated json file size: 4.7MiB
Generating HTML report
Report saved.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/viztracer/main.py", line 363, in exit_routine
    exit(0)
  File "/usr/lib/python3.5/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 0
```

**Comment by gaogaotiantian** [comment]
Hi,

Unfortunately, VizTracer does not support python2, because python2 is not even officially supported by python community anymore. And for the same reason, I will not make effort to make VizTracer work with python2, sorry about that.

VizTracer supports all python versions that are officially supported(not end-of-life), 3.6-3.9 for now. I would also recommend that you start using these version for your applications.

The reason your `pip3` did not work was because `nova` is not installed for python3.5, which is the python3 you are using, and, unfortunately is not supported by now. As far as I can tell, `nova` supports all modern python versions, so you can upgrade your python(or rather install the newer version of python), install `nova` under that python(maybe use virtual environment?), then apply the changes required for your application so it can run with python3. I would say this is recommended, with or without the usage of VizTracer.

I'll close this issue for now, if you have more questions, feel free to comment.
