### ISSUE TITLE
Names instead of tip and pid

### ISSUE THREAD

**Issue by anton-buyskikh** [gaogaotiantian/viztracer#61]
Is it possible to use `threading.Thread.name` and `multiprocessing.Process.name` instead of `tid` and `pid`?

Inspeaction of json files showed that names are not currently saved.

**Comment by gaogaotiantian** [comment]
Replacing is not possible because python does not force the name of `Thread` or `Process` to be unique, also chrome trace event format does not support that.

However, it does support process name and thread name as metadata, which will display the names alongside the id. 

There are a couple things to sort out. For example, multiprocessing is not the only multi-process we supported. I'll take a look into this, and I do believe thread name and process name could be more meaningful.

**Comment by gaogaotiantian** [comment]
@anton-buyskikh , this feature is added in master. It will be included in the next release.

**Comment by anton-buyskikh** [comment]
@gaogaotiantian fantastic! Thank you very much for this quick reply!

**Comment by ItaiOfir** [comment]
Hi, love using viztracer and very much looking forward to this feature! Any word when this next release will be out?

**Comment by gaogaotiantian** [comment]
Hi, I'm glad that you enjoy using VizTracer. I know it's been a while since last release(well it's been less than 3 weeks..). Rest assured that I'm working on this release for you guys now. There will be a rather large new feature - plugins for this release and I want to polish the first official plugins before I release the feature. I'm expecting that I'll release 0.11.0 probably in one or two weeks. I hope that you won't wait too long for this :)

**Comment by ItaiOfir** [comment]
Amazing! Thanks for the fast response, plugins sound great definitely looking forward to those too!

**Comment by gaogaotiantian** [comment]
@ItaiOfir just letting you know that this feature is released with 0.11.0 just now.

**Comment by ItaiOfir** [comment]
Just checked it out, works great! thank you so much :)
