### ISSUE TITLE
Interface for stacktraces

### ISSUE THREAD

**Issue by maartenbreddels** [gaogaotiantian/viztracer#63]
It would be nice to have a function to get a `list[str]` as function of the time. I plan to take viztracer's output to inject stacktraces back into perf, which can sample at a regular interval, this should allow us to create the FlameGraph tools https://github.com/brendangregg/FlameGraph to make offcpu/offgil flamegraphs etc.

Do you think it makes sense to include this in viztracer?

**Comment by gaogaotiantian** [comment]
First of all, VizTracer has the tools to create flamegraph. https://github.com/gaogaotiantian/viztracer/blob/master/src/viztracer/flamegraph.py

Secondly, it does not make sense to me to port VizTracer's output to perf. It would make sense to me if it's the other direction. There are a lot of tools that are sampling profilers and can generate flamegraph. Maybe perf itself can generate enough data to create a flamegraph. The purpose of VizTracer is to show the execution details of the program. Having extra data(GIL, memory, core consumption) is good, but it's not the other way around. That says, you can have the other kind of data with less overhead with other tools.

Also, I did not quite get the idea of making offcpu/offgil flamegraphs. Do you mean flamegraph when GIL is not on the thread? Or flamegraph that excludes GIL impact?

**Comment by maartenbreddels** [comment]
> First of all, VizTracer has the tools to create flamegraph. https://github.com/gaogaotiantian/viztracer/blob/master/src/viztracer/flamegraph.py

Cool, so much in this project, I'll check it out.



> Secondly, it does not make sense to me to port VizTracer's output to perf.

The point is, that perf gives you a system/kernel stacktrace, but the Python stacktrace is lacking, so you are lost as what is going on between Python and the kernel, so it's not the flamegraph per see, but the kernel information lost (see https://youtu.be/BHA65BqlqSk?t=583 at this specific timestamp if you are interested.

So, I want to recover the stacktrace, and I think viztracer is actually also the perfect tool for that. I could make my own tool to store stacktraces, but viztracer is 99% there. Or do you see a cheaper way to record Python stacktraces?

Also, I have some viztracer outputs (for 64 threads) which are difficult to analyze, and a flamegrapgh that gives me more statistical information (who's spending a lot of time holding the GIL for instance) can be useful in addition to viztracer.

**Comment by gaogaotiantian** [comment]
Flamegraph is definitely useful when a summary is preferred, and that's why I actually implemented it pretty early in the project(even though people are not using it hence less maintenance). 

Accessing data at a specific timestamp is not trivial for data like chrome trace format. However, I think the code is in there(probably not where you would be looking for).. 

There's a tool called `vdb`. Where it performs like `pdb`, but takes an input of the json report of VizTracer. There's a feature in it to "go to a specific timestamp". And there's a feature to "list the call stack". Maybe you want to take a look at the code https://github.com/gaogaotiantian/viztracer/blob/master/src/viztracer/prog_snapshot.py#L373 . 

Like I said, it's not super trivial to reconstruct the call stack from the chrome trace events(or if you feel differently, you can always start with the json file, parse and reconstruct with your own tools). Maybe reuse some of the code, or even the data structures from VizTracer(you can use `ProgSnapshot` by itself) will make it easier?

**Comment by maartenbreddels** [comment]
Great, those are the pointers I needed, and happy to see the bisect, that was already in the pseudocode in my mind. I'll see if I can use this for what I need, thanks!

**Comment by gaogaotiantian** [comment]
Seems like there's nothing left to discuss at this point. I'll close this issue.
