### ISSUE TITLE
A lot of noise when running with `-m` (as module) compared to a script

### ISSUE THREAD

**Issue by maartenbreddels** [gaogaotiantian/viztracer#81]
Two equivalent methods:
```
$ viztracer -o example1.html per4m/example1.py                                                                                                                                                                         dev
Loading finish                                        
Saving report to /home/maartenbreddels/github/maartenbreddels/per4m/example1.html ...
Dumping trace data to json, total entries: 94, estimated json file size: 11.0KiB
Generating HTML report
Report saved.

$ viztracer -o example1.html -m per4m.example1                                                                                                                                                                         dev
Loading finish                                        
Saving report to /home/maartenbreddels/github/maartenbreddels/per4m/example1.html ...
Dumping trace data to json, total entries: 488664, estimated json file size: 55.9MiB
Generating HTML report
Report saved.
```

Where the second generates a huge json/html. The tracing shows all the nice:

![image](https://user-images.githubusercontent.com/1765949/103747718-5bc9ae00-5003-11eb-932d-f12582210286.png)

**Comment by gaogaotiantian** [comment]
So, I don't believe ``python -m package.module`` and ``python package/module.py`` are equivalent under the rug. The former requires more searching(the noise you are mentioning). 

VizTracer shows what really happened, rather than what seemed to happen, so personally I won't call it "noise". 

There are easy ways to filter it out though, just add ``--ignore_non_file`` and all the import stuff will be ignored. 

Actually, if you time the two methods, you may find that they spend different time to execute.

**Comment by maartenbreddels** [comment]
> There are easy ways to filter it out though, just add `--ignore_non_file` and all the import stuff will be ignored.

That seems to filter out too much.

What I'm now doing with 'giltracer', is to assume the module has a `main(argv)` function, and call that, generating a >50MB HTML for me isn't really a workable solution because I generate them remotely.

Another thing I've done is to include an `--import='numpy,pandas,whatever'` argument, so get rid of some noise, maybe you can support that as well?

**Comment by gaogaotiantian** [comment]
Oh, the ``--ignore_non_file`` filtering out everything is a bug. I'll fix it soon. It won't work with ``-m`` now.

pre-import libraries to reduce the number of entries seems sketchy to me. This problem should be fixed with ``--ignore_non_file`` as long as I fixed the bug(and maybe renaming it to ``ignore_import``). 

For now, there are a couple of options that you can try. 
* Since you always need the latter part of the program, you could try to limit the buffer size to a number that's workable for remote. ``viztracer --tracer_entries 1000`` maybe?
* If file size is critical to you, try the ``gz`` file? ``viztracer -o report.gz``. You can load it directly from ``chrome://tracing``. (Of course, without the source code because that's the hack I had for the html)
* To make it even more delicate, you can actually implement your own filter plugin. However if you only need to get rid of the import part, this seems like an overreach. 

Anyway, I'll try to fix the bug in 24 hours and hopefully it will work for you.

**Comment by gaogaotiantian** [comment]
I fixed the issue and renamed the ``--ignore_non_file`` to ``--ignore_frozen``. This is released with 0.11.1. So you could try updating your viztracer to the latest and run with ``--ignore_frozen`` to filter out the import stuff.

**Comment by gaogaotiantian** [comment]
Do you think the new option ```ignore_frozen``` is working for you that this issue could be closed?

**Comment by maartenbreddels** [comment]
I need to check with the other -m fix if all is working properly, will
let you know asap (working on an article that uses this all)

(from mobile phone)

**Comment by gaogaotiantian** [comment]
The article is posted and well-received. I'll close this issue.
